name: Deploy Sitemap
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
