name: Fix Jekyll
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .nojekyll
        run: |
          touch .nojekyll
          echo "Bu dosya GitHub Pages'in Jekyll'i atlamasını sağlar" > README.md
      - uses: actions/upload-pages-artifact@v2
